apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev-cluster
  region: us-east-1

managedNodeGroups:
- name: myclusternodegroup
  instanceType: t3.medium
  desiredCapacity: 1
  minSize: 1
  maxSize: 2

