apiVersion: eksctl.io/v0.1.40
kind: ClusterConfig

metadata:
  name: dev-cluster
  region: us-east-1
  version: "1.29"

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
